export const DEFAULT_USER_NAME = 'NateLu Clone';
export const DEFAULT_USER_POINTS = 10;
export const SCALE_RIVER_HEIGHT = 0.7;

export const levelPoints: { [key: number]: number } = {
    1: 15,
    2: 20,
    3: 25,
    4: 30,
    5: 35,
    6: 40,
    7: 45,
    8: 50,
    9: 55,
    10: 60,
};

export const congratsMessages = [
    "Way to go!",
    "You did it!",
    "Congratulations!",
    "Great job!",
    "Awesome!",
    "Well played!",
    "Nice work!",
    "Superb!",
    "Excellent!",
    "Brilliant!",
    "Fantastic!",
    "Well deserved!",
    "You're killing it!",
    "Keep it up!",
    "Impressive!",
    "Outstanding!",
    "Terrific job!",
    "You rock!",
    "Amazing work!",
    "Hooray for you!",
    "You're a star!",
    "Well earned!",
    "Thumbs up!",
    "Good going!",
    "Top-notch!",
    "High five!",
    "You're on fire!",
    "Rocking it!",
    "Spectacular!",
    "Kudos to you!",
    "Champion status!",
    "You're unstoppable!",
    "Party time!",
    "Woot woot!",
    "Score!",
    "Bravo!",
    "Celebration time!",
    "Keep it up!",
    "Proud of you!",
    "Hip hip hooray!",
    "You're a winner!",
    "Doing great!",
    "Happy dance!",
    "You're the best!",
    "Cheers to you!",
    "Woohoo!",
    "Victory is yours!",
    "You're amazing!",
    "Mission accomplished!",
    "You earned it!",
];
