export const defaultUserName = 'NateLu Clone';
export const defaultUserPoints = 0;

export const levelPoints: { [key: number]: number } = {
    1: 15,
    2: 20,
    3: 25,
    4: 30,
    5: 35,
    6: 40,
    7: 45,
    8: 50,
    9: 55,
    10: 60,
};

export const congratsMessages = [
    "Points unlocked, mission accomplished!",
    "Congratulations, points acquired with style!",
    "Points awarded, victory achieved!",
    "Scoreboard dancing, points in your favor!",
    "You're a point-earning champion!",
    "Points collected, celebration initiated!",
    "Kudos on the epic point gain!",
    "Pointastic performance, well deserved!",
    "You've leveled up your points game!",
    "Party time: Points galore!",
    "Points accumulated, celebrate your success!",
    "Points champion, bask in your glory!",
    "Point-tastic triumph, enjoy the moment!",
    "You've earned points like a boss!",
    "Points unlocked, happiness overflowing!",
    "Scoreboard conquered, points dominated!",
    "Well played, point enthusiast!",
    "Points harvested, mission complete!",
    "Congratulations, points earned with flair!",
    "Point hunter extraordinaire, celebrate now!",
    "Points in your pocket, time to party!",
    "You're a point-gathering genius!",
    "Bravo! Point collection mastery achieved!",
    "Points earned, let the celebration begin!",
    "You've hit the point jackpot, incredible!",
    "Points captain, leading the way!",
    "Well done, points superstar!",
    "Collecting points like a pro, congrats!",
    "Scoreboard conquered, points under control!",
    "Points unlocked: Happiness level up!",
    "You've earned points like a champ!",
    "Point-tastic victory, well deserved!",
    "Congratulations on the magnificent point win!",
    "Points magician, your skills are amazing!",
    "You're a point-earning virtuoso!",
    "Brilliant point collection, pure genius!",
    "Points in your pocket, time to celebrate!",
    "You've reached new heights of point earning!",
    "Points conqueror, the world applauds!",
    "Congratulations on the incredible point gain!",
    "You've earned points with style and grace!",
    "Point gathering brilliance, well done!",
    "Party time: Points celebration activated!",
    "Congrats on the point dominion, keep it up!",
    "You're the champion of point accumulation!",
    "Points slayer, we bow to your greatness!",
    "You've cracked the code of earning points!",
    "Well done, point-gathering prodigy!",
    "Congratulations, points champion in the making!",
    "You're a points superhero now, celebrate big!",
    "Points earned: The universe applauds!",
];
